import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { parseInput, validateResult, relativePosition, focusViewport, clampInterval, filterMetrics, rangeSummary, trackGeometry, metricCSV, exportedTracks, metricUnit, exportedSequence } from '../src/model.ts';
if (!process.env.GUI_FIXTURE) throw Error('Run npm run test:gui to generate native fixtures.');
const result = JSON.parse(readFileSync(process.env.GUI_FIXTURE));
const t=(ja,en)=>en;
test('cleavage coordinate convention has no zero',()=>{assert.equal(relativePosition(18,18),-1);assert.equal(relativePosition(19,18),1);assert.equal(relativePosition(16,18),-3);assert.equal(relativePosition(1,null),null)});
test('single FASTA validation catches multi-record input including CRLF',()=>{assert.equal(parseInput('>one\r\nMK\r\nLA'),'MKLA');assert.throws(()=>parseInput('>a\r\nMK\r\n>b\r\nLA'));assert.equal(parseInput(' MKLA '),'MKLA')});
test('imported result rejects reversed intervals and mismatching residues',()=>{assert.equal(validateResult(result),result);let bad=structuredClone(result);bad.metrics[0].range=[3,1];assert.throws(()=>validateResult(bad));bad=structuredClone(result);bad.profiles[0].residue='A';assert.throws(()=>validateResult(bad));bad=structuredClone(result);bad.annotations.cleavage.value=27;assert.throws(()=>validateResult(bad))});
test('viewport encloses selected ranges at both termini and for long sequences',()=>{for(const length of [1,26,10000]){for(const interval of [[1,1],[length,length],[1,length]]){const v=focusViewport(interval,length);assert(v[0]>=1&&v[1]<=length);assert(v[0]<=interval[0]&&v[1]>=interval[1]);}}assert.deepEqual(clampInterval(100,-1,26),[1,26])});
test('independent filters produce exact rows and exported count',()=>{const filters={scope:'SP',property:'hydrophobicity',process:'targeting',query:'',estimates:true};const rows=filterMetrics(result,filters);assert(rows.length>0);assert(rows.every(m=>m.scope==='SP'&&m.property==='hydrophobicity'&&m.processes.includes('targeting')));assert.equal(metricCSV(rows).split('\r\n').length,rows.length+1);assert.equal(filterMetrics(result,{...filters,query:'not-a-descriptor'}).length,0);assert(!filterMetrics(result,{scope:'',property:'',process:'',query:'',estimates:false}).some(m=>m.basis==='rule_estimate'))});
test('selected interval summary agrees with native stored SP means',()=>{const summary=rangeSummary(result,[1,18]);for(const [key,value] of Object.entries(summary)){assert(Math.abs(value-result.metrics.find(m=>m.id==='SP.'+key).value)<1e-12)}const point=rangeSummary(result,[19,19]);assert.equal(point.hydrophobicity,result.profiles[18].hydrophobicity)});
test('track y axes stay fixed across viewport changes; single residue is finite',()=>{const a=trackGeometry(result,'hydrophobicity',[1,26]),b=trackGeometry(result,'hydrophobicity',[13,24]),single=trackGeometry(result,'charge',[19,19]);assert.equal(a.lo,b.lo);assert.equal(a.hi,b.hi);assert.equal(a.y(0),b.y(0));assert(!single.points.includes('NaN'));assert.equal(a.x(1),58);assert.equal(a.x(26),976)});
test('exports preserve source, selection coordinates and safety',()=>{const svg=exportedTracks(result,['hydrophobicity','charge','flexibility'],[13,24],[18,19],19,t);assert.equal((svg.match(/<svg/g)||[]).length,3);assert.match(svg,/KYTJ820101/);assert.match(svg,/−1 │ \+1/);assert.match(metricCSV(result.metrics),/boundary_basis/);assert.equal(metricUnit(result.metrics.find(m=>m.id==='SP.fraction_A'),t),'fraction (0–1)')});

test('sequence figure retains boundary provenance and unknown states',()=>{const svg=exportedSequence(result,[1,24],19,true,t);assert.match(svg,/Signal peptide/);assert.match(svg,/−1 │ \+1/);assert.match(svg,/N\/H\/C basis/);const unknown=structuredClone(result);unknown.annotations.cleavage={value:null,basis:'missing'};unknown.regions.intervals=null;assert.match(exportedSequence(unknown,[1,24],1,false,t),/Cleavage unspecified/);});
