import React from 'react';
import { properties, scales, sourceURL, type Translate } from './model';
export function Guide({ t }: { t: Translate }) {
  return <div className="guide-content"><h2>{t('結果の読み方', 'Reading the results')}</h2><ol><li>{t('結果上部で、SPの有無、切断位置、種類と、それぞれの情報の由来を確認します。', 'Check SP presence, cleavage, type and their individual provenance in the result header.')}</li><li>{t('配列画面で領域を選びます。残基をクリックすると一点、Shiftを押してクリックすると範囲を選べます。開始・終了位置の入力でも範囲を指定できます。', 'Select intervals in the Sequence view. Click selects one residue; Shift-click extends a range. Start and end fields also select an interval.')}</li><li>{t('指標一覧で集計範囲や特性を絞り込みます。各行の定義・出所を開くと、尺度と計算方法を確認できます。', 'Filter Metrics by interval and property. Open each row to inspect the definition, scale and source.')}</li><li>{t('解析JSONは全結果と表示設定の保存、CSVは数値の利用、SVGは図の編集、HTMLは解析条件と全指標の持ち出しに使います。', 'Use analysis JSON to restore results and settings; CSV for data, SVG for editable figures, and HTML for a report with all descriptors and settings.')}</li></ol>
    <h2>{t('配列の物性尺度', 'Sequence property scales')}</h2><p>{t('物性トラックは各残基の参照尺度です。領域別指標と選択範囲の集計では、その算術平均を使います。グラフの平滑化は行っていません。', 'Tracks show raw residue coefficients. Interval summaries use arithmetic means. Tracks are not smoothed.')}</p><div className="table-container"><table className="scale-table"><thead><tr><th>{t('特性', 'Property')}</th><th>{t('尺度', 'Scale')}</th><th>{t('解釈', 'Interpretation')}</th></tr></thead><tbody>{properties.slice(0, 6).map(key => <tr key={key}><th>{t(scales[key].ja, scales[key].en)}</th><td>{scales[key].source}{scales[key].code && <small><a href={sourceURL(scales[key].code!)!} target="_blank" rel="noreferrer">{scales[key].code}</a></small>}</td><td>{t(scales[key].note, scales[key].noteEn)}</td></tr>)}</tbody></table></div>
    <h3>{t('N/H/Cの領域推定', 'N/H/C region estimation')}</h3><p>{t('既知の境界がない場合、SP内部でKyte–Doolittle尺度の合計が最大となる正の区間をH領域の候補とし、その前後をNとCに分けます。配列を探索するための規則で、生物学的な領域を検証した方法ではありません。SPの終端が分かり、種類が未指定またはSec/SPIの場合に限って適用します。', 'Without supplied boundaries, an internal positive segment with maximum Kyte–Doolittle sum defines an exploratory H-region, with N/C on either side. This is a browsing rule, not a validated biological predictor. It applies when the endpoint is known and type is unspecified or Sec/SPI.')}</p>
    <h3>{t('TSignalの予測と入力注釈', 'TSignal predictions & supplied annotations')}</h3><p>{t('TSignalはシグナルペプチドの有無、種類、切断位置を予測するモデルです。自動予測が利用できる場合、未入力の注釈を補います。入力した注釈が優先され、元の予測も解析JSONに保持します。接続状態は入力画面で確認できます。上流実装に従い、予測には先頭70残基までを使います。', 'TSignal predicts SP presence, type and cleavage. When available, it fills missing annotations. Supplied annotations take precedence and original predictions are retained in JSON. Availability is shown on the input page. Upstream inference uses up to the first 70 residues.')}</p><p><a href="https://github.com/Dumitrescu-Alexandru/TSignal" target="_blank" rel="noreferrer">{t('TSignalの上流実装', 'TSignal upstream implementation')}</a></p>
    <h3>{t('peptides.pyとの役割の違い', 'Relationship to peptides.py')}</h3><p>{t('peptides.pyは汎用のペプチド物性計算を提供します。本ツールはシグナルペプチドに特化し、前駆体上の座標、切断点前後、SP・N/H/C・成熟側の集計範囲、注釈の由来を合わせて確認できるようにしています。', 'peptides.py provides general peptide descriptors. This tool specializes in signal peptides: precursor coordinates, cleavage context, SP/N/H/C/mature intervals and annotation provenance.')}</p>
    <h3>{t('構造注釈と参照尺度の区別', 'Structural annotations and reference scales')}</h3><p>{t('相対溶媒露出度は、構造中の残基の露出の程度を表す値です。外部注釈のrsaとして0〜1で読み込みます。無秩序の注釈はdisorder、二次構造はsecondary_structureで読み込めます。値の意味や予測の信頼度は、元の方法と構造状態を確認してください。柔軟性参照値から実際の剛直性を求めることはできません。', 'Relative solvent accessibility describes residue exposure in a structure and is imported as rsa (0–1). Import disorder and secondary_structure separately. Interpretation and confidence depend on the source method and structural state. Flexibility coefficients do not measure physical rigidity.')}</p>
    <h3>{t('解析結果の保存と再現', 'Saving & reproducibility')}</h3><p>{t('保存JSONには配列、注釈、集計設定、計算結果、実装と入力配列のSHA256が含まれます。SHA256は内容を識別する値で、恒久的な公開解析IDではありません。履歴はページを閉じると消えるため、再利用する結果は保存してください。', 'Saved JSON includes sequence, annotations, settings, results and SHA256 hashes for the implementation and sequence. Hashes identify content; they are not permanent public analysis IDs. Session history is lost when the page closes, so save results for reuse.')}</p><p><a href="https://github.com/yktsnd/signal-peptide-features" target="_blank" rel="noreferrer">{t('ソースコード・計算仕様', 'Source code & specification')}</a></p>
  </div>;
}
