import React, { useEffect, useState } from 'react';
export function UsageAdmin(){
 const [days,setDays]=useState('7'),[report,setReport]=useState<any>(null),[error,setError]=useState(''),[events,setEvents]=useState<any[]>([]),[truncated,setTruncated]=useState(false),[busy,setBusy]=useState(false);
 async function load(){setBusy(true);setError('');try{const r=await fetch('/api/telemetry/report?days='+days);if(r.status===403){setError('この画面はサイト所有者のみ利用できます。ChatGPTでサインインしてください。');return;}if(!r.ok)throw Error();setReport(await r.json());}catch{setError('集計を取得できませんでした。接続状態を確認してください。');}finally{setBusy(false);}}
 useEffect(()=>{void load();},[days]);
 async function timeline(session:string){const r=await fetch('/api/telemetry/report?days='+days+'&session='+encodeURIComponent(session));if(!r.ok){setError('操作履歴を取得できませんでした。');return;}const v=await r.json();setEvents(v.events||[]);setTruncated(!!v.truncated);}
 const total=(name:string)=>(report?.daily||[]).filter((r:any)=>r.event===name).reduce((n:number,r:any)=>n+r.total,0);
 function save(){const a=document.createElement('a');const url=URL.createObjectURL(new Blob([JSON.stringify({report,timeline:events},null,2)],{type:'application/json'}));a.href=url;a.download='usage-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <><header className="site-header"><a href="/">Signal Peptide Explorer</a><span>利用状況 · 所有者用</span></header><main className="usage-admin"><h1>使いやすさの改善レポート</h1><p>同意した利用者の操作だけを集計します。離脱や繰り返し操作は、問題の候補であり、原因の確定ではありません。</p><div className="button-group"><label>対象期間<select value={days} onChange={e=>setDays(e.target.value)}><option value="7">7日</option><option value="30">30日</option></select></label><button disabled={busy} onClick={()=>void load()}>更新</button><button disabled={!report} onClick={save}>集計と選択履歴をJSONで保存</button></div>
 {error&&<div className="notice" role="alert">{error} <a href="/signin-with-chatgpt?return_to=%2Fadmin" target="_top">ChatGPTでサインイン</a></div>}
 {report&&<><section className="panel"><h2>記録の範囲</h2><p>{report.health.sessions}セッション · 個別イベント {report.health.events}件</p><p>個別記録30日、日別集計180日。削除済みの個別記録に対応する集計も残るため、個別記録と日別集計の件数は一致しない場合があります。</p><table><thead><tr><th>段階</th><th>回数</th></tr></thead><tbody>{[['解析開始','analysis_started'],['解析完了','analysis_completed'],['解析失敗','analysis_failed'],['範囲・残基の選択','selection_changed'],['出力要求','export_requested'],['出力生成','export_generated']].map(([label,key])=><tr key={key}><th>{label}</th><td>{total(key)}</td></tr>)}</tbody></table><p>上記はイベント回数です。タスク達成率や、ファイルの保存完了を表す値ではありません。</p></section>
 <section className="panel"><h2>日別・画面別の操作</h2><div className="table-container"><table><thead><tr><th>日</th><th>UI</th><th>操作</th><th>画面</th><th>端末幅</th><th>入力手段</th><th>結果</th><th>回数</th><th>平均処理時間</th></tr></thead><tbody>{report.daily.map((r:any,i:number)=><tr key={i}><td>{r.day}</td><td>{r.ui}</td><td>{r.event}</td><td>{r.screen}</td><td>{r.width}</td><td>{r.modality}</td><td>{r.outcome}</td><td>{r.total}</td><td>{r.duration_sum?Math.round(r.duration_sum/r.total)+' ms':'—'}</td></tr>)}</tbody></table></div><p>最大2,000行を表示。更新前後はUI版と端末幅を揃えて比較してください。</p></section>
 <section className="panel"><h2>操作部品ごとの利用</h2><p>識別子はソースコードと操作台帳に対応します。最大200行。</p><table><thead><tr><th>操作部品</th><th>操作</th><th>回数</th></tr></thead><tbody>{(report.controls||[]).map((r:any,i:number)=><tr key={i}><td>{r.control}</td><td>{r.event}</td><td>{r.total}</td></tr>)}</tbody></table></section>
 <section className="panel"><h2>処理・滞在時間の分布</h2><p>最近の最大5,000件から算出。滞在時間は使用感や達成を表しません。</p><table><thead><tr><th>操作</th><th>UI</th><th>端末幅</th><th>件数</th><th>中央値</th><th>95パーセンタイル</th></tr></thead><tbody>{(report.timings||[]).map((r:any,i:number)=><tr key={i}><td>{r.event}</td><td>{r.ui}</td><td>{r.width}</td><td>{r.count}</td><td>{Math.round(r.p50)} ms</td><td>{Math.round(r.p95)} ms</td></tr>)}</tbody></table></section>
 <section className="panel"><h2>操作の遷移</h2><table><thead><tr><th>前の操作</th><th>次の操作</th><th>回数</th></tr></thead><tbody>{report.transitions.map((r:any,i:number)=><tr key={i}><td>{r.from_event}</td><td>{r.to_event}</td><td>{r.total}</td></tr>)}</tbody></table></section>
 <section className="panel"><h2>任意の使用感評価</h2><table><thead><tr><th>タスク</th><th>難しさ</th><th>達成状況</th></tr></thead><tbody>{report.feedback.map((r:any,i:number)=>{let p:any={};try{p=JSON.parse(r.props);}catch{}return <tr key={i}><td>{p.task}</td><td>{p.difficulty}</td><td>{p.outcome}</td></tr>;})}</tbody></table><p>回答者の自己評価です。最大100件。</p></section>
 <section className="panel"><h2>操作タイムライン</h2><p>最近100セッション。研究内容を含まない操作の順序を確認します。</p><div className="table-container"><table><thead><tr><th>セッション</th><th>開始</th><th>イベント</th><th>確認</th></tr></thead><tbody>{report.sessions.map((r:any)=><tr key={r.session}><td><code>{r.session.slice(0,8)}</code></td><td>{new Date(r.started).toLocaleString('ja-JP')}</td><td>{r.events}</td><td><button onClick={()=>void timeline(r.session)}>履歴を見る</button></td></tr>)}</tbody></table></div>{truncated&&<p>先頭500イベントまでを表示しています。</p>}<ol className="usage-timeline">{events.map((r:any)=>{let p:any={};try{p=JSON.parse(r.props);}catch{}return <li key={r.id}><time>{new Date(r.at).toLocaleTimeString('ja-JP')}</time> <b>{r.event}</b> <code>{JSON.stringify(p)}</code></li>;})}</ol></section></>}
 </main></>;
}
