import React, { useEffect, useState } from 'react';
import { deleteUsageData, initTelemetry, setUsageConsent, telemetryState, track } from './telemetry';
import type { Translate } from './model';
export function UsageSettings({t}:{t:Translate}){
  const [state,setState]=useState(telemetryState),[open,setOpen]=useState(false),[message,setMessage]=useState(''),[working,setWorking]=useState(false);
  const [task,setTask]=useState('inspect_plus1'),[difficulty,setDifficulty]=useState('3'),[completed,setCompleted]=useState('success');
  useEffect(()=>{const update=()=>setState(telemetryState());window.addEventListener('ux-state',update);initTelemetry();update();return()=>window.removeEventListener('ux-state',update);},[]);
  async function choose(value:'yes'|'no'){setWorking(true);await setUsageConsent(value);setWorking(false);setMessage(value==='yes'?t('設定を更新しました。下の収集状態を確認できます。','Preference updated. Check collection status below.'):t('操作記録の収集を停止し、未送信の記録を消去しました。','Collection stopped and pending events cleared.'));}
  return <aside className="usage-settings" aria-label={t('利用状況の記録設定','Usage recording settings')}>
    {(state.consent==='unset'||open)&&<div className="usage-panel"><h2>{t('使いやすさの改善に協力する','Help improve usability')}</h2><p>{t('操作の流れと待ち時間を記録します。配列・入力文字・解析値は送りません。記録しなくても解析できます。','Record actions and latency. No sequences, input text or analysis values are sent. Analysis works without recording.')}</p><details className="usage-policy"><summary data-ux="usagesettings-summary-policy">{t('記録する情報・保存期間','Collected information & retention')}</summary><p>{t('操作の種類・順序、待ち時間、エラーの分類、端末幅などを記録します。画面画像、ファイル名、アカウント情報は記録しません。','Records action categories, order, latency, error categories and screen width. No screen images, filenames or account information.')}</p><p>{t('個別記録は30日、個人と結び付けない日別集計は180日保持します。ランダムな記録IDで操作を関連付けます。','Individual records are retained for 30 days; daily counts without personal IDs for 180 days. A random recording ID links actions.')}</p><p>{t('期限を過ぎた記録は、収集開始や管理画面へのアクセス時に削除します。','Expired records are pruned on registration or report access.')}</p></details>
    <div className="button-group"><button data-ux="usagesettings-button-001" disabled={working||!state.enabled} onClick={()=>void choose('yes')}>{t('操作記録を許可','Allow usage recording')}</button><button data-ux="usagesettings-button-002" disabled={working} onClick={()=>void choose('no')}>{t('記録しない','Do not record')}</button>{open&&<button data-ux="usagesettings-button-003" onClick={()=>setOpen(false)}>{t('閉じる','Close')}</button>}</div>
    <p className="usage-state" role="status">{t('収集状態','Collection')}: {!state.enabled?t('接続確認中、または収集基盤が利用できません','Checking connection, or collection service unavailable'):state.consent==='yes'&&state.collecting&&!state.error?t('有効','Enabled'):state.consent==='yes'?t('送信待ち／再試行中','Pending / retrying'):t('停止','Stopped')} · {state.pending} {t('件が送信待ち','pending events')}</p>
    {open&&<><p>{t('削除するとこの端末の記録IDに対応する個別記録を消去します。個人と結び付かない日別集計は残ります。ブラウザーの保存領域を消去すると、以前の記録IDにはアクセスできなくなります。','Deletion removes individual records for this browser recording ID. Unlinked daily counts remain. Clearing browser storage removes access to the previous ID.')}</p><button data-ux="usagesettings-button-004" disabled={working} onClick={async()=>{setWorking(true);const ok=await deleteUsageData();setMessage(ok?t('個別記録を削除しました。','Individual records deleted.'):t('収集は停止しました。サーバーでの削除を完了できなかったため、接続後に再試行してください。','Collection stopped. Server deletion could not be completed; retry when connected.'));setWorking(false);}}>{t('記録を削除して停止','Delete records and stop')}</button>
    <details><summary data-ux="usagesettings-summary-005">{t('使いやすさを評価する（任意）','Rate usability (optional)')}</summary><p>{t('操作記録が有効な場合に送信できます。自由記述や配列の送信はありません。','Available when recording is enabled. No free text or sequences are sent.')}</p><div className="form-row"><label>{t('調べたこと','Task')}<select data-ux="usagesettings-select-006" value={task} onChange={e=>setTask(e.target.value)}><option value="inspect_plus1">{t('＋1を確認','Inspect +1')}</option><option value="aggregate_interval">{t('範囲を集計','Aggregate interval')}</option><option value="inspect_source">{t('根拠を確認','Inspect source')}</option><option value="save_restore">{t('保存・再開','Save / restore')}</option><option value="other">{t('その他','Other')}</option></select></label><label>{t('難しさ（1=簡単、5=難しい）','Difficulty (1=easy, 5=hard)')}<select data-ux="usagesettings-select-007" value={difficulty} onChange={e=>setDifficulty(e.target.value)}>{['1','2','3','4','5'].map(v=><option key={v}>{v}</option>)}</select></label><label>{t('目的を達成できましたか','Did you complete the task?')}<select data-ux="usagesettings-select-008" value={completed} onChange={e=>setCompleted(e.target.value)}><option value="success">{t('できた','Yes')}</option><option value="failed">{t('できなかった','No')}</option><option value="unknown">{t('まだ途中','In progress')}</option></select></label></div><button data-ux="usagesettings-button-009" disabled={state.consent!=='yes'||!state.enabled||!state.collecting} onClick={()=>{track('feedback_submitted','feedback',{task,difficulty,outcome:completed});setMessage(t('評価を送信待ちに追加しました。','Feedback queued.'));}}>{t('評価を送る','Send rating')}</button></details></>}
    {message&&<p role="status">{message}</p>}</div>}
    <button data-ux="usagesettings-button-010" className="text-button" onClick={()=>setOpen(!open)}>{t('操作記録・使いやすさの評価','Usage recording & usability feedback')}</button>
  </aside>;
}
