import React, { useEffect, useState } from 'react';
import { FileButton, type RecordEntry, type View } from './App';
import { Guide } from './Guide';
import { track } from './telemetry';
import { contract } from '../../telemetry/contract.mjs';
import { SequenceViewer } from './SequenceViewer';
import { basisLabel, clampInterval, exportedTracks, filterMetrics, focusViewport, formatValue, metricCSV, metricDefinition, metricUnit, properties, safeHTML, saveFile as baseSaveFile, scales, scopeLabel, sourceURL, warningLabel, type Interval, type Metric, type Result, type Translate } from './model';
function saveFile(name: string, text: string, type?: string) {
  const kind=name.endsWith('.csv')?'csv':name.endsWith('.svg')?'svg':name.endsWith('.html')?'html':'json';
  try { baseSaveFile(name,text,type); track('export_generated','export',{kind,outcome:'success'}); }
  catch { track('export_failed','export',{kind,outcome:'failed',error:'runtime'}); throw Error('Export could not be generated'); }
}
const processNames: Record<string, [string, string]> = { targeting: ['標的への誘導', 'Targeting'], orientation: ['膜内での向き', 'Membrane orientation'], translocation: ['膜を通る過程', 'Translocation'], recognition: ['切断部位の認識', 'Cleavage-site recognition'], accessibility: ['切断部位への接近', 'Cleavage-site accessibility'], selection: ['切断位置の選択', 'Cleavage-site selection'] };
function processLabel(key: string, t: Translate) { return processNames[key] ? t(...processNames[key]) : key; }
function recordName(record: RecordEntry, t: Translate) { return record.metadata.name || t('名称未指定の配列', 'Unnamed sequence'); }
function annotationLabel(result: Result, key: string, t: Translate) {
  const value = result.annotations[key].value;
  if (key === 'has_sp') return value === true ? t('あり', 'Present') : value === false ? t('なし', 'Absent') : t('不明', 'Unknown');
  if (key === 'cleavage') return value == null ? t('不明', 'Unknown') : `${value} │ ${Number(value) < result.sequence.length ? Number(value) + 1 : t('成熟側未入力', 'mature side absent')}`;
  return String(value || t('不明', 'Unknown'));
}
export function ResearchWorkspace({ record, history, t, onEdit, onRestore, onOpen, onView }: { record: RecordEntry; history: RecordEntry[]; t: Translate; onEdit: (target?: 'cleavage' | 'structure') => void; onRestore: (record: RecordEntry) => void; onOpen: (file: File) => void; onView?: (view: View) => void }) {
  const result = record.analysis, length = result.sequence.length, cut = result.annotations.cleavage.value as number | null, saved = record.view;
  const defaultSelection: Interval = cut != null ? [Math.max(1, cut - 5), Math.min(length, cut + 6)] : [1, Math.min(length, 70)];
  const validInterval = (v: unknown): v is Interval => Array.isArray(v) && v.length === 2 && v.every(n => Number.isInteger(n) && n >= 1 && n <= length) && v[0] <= v[1];
  const [selection, setSelection] = useState<Interval>(validInterval(saved?.selection) ? saved!.selection! : defaultSelection);
  const [viewport, setViewport] = useState<Interval>(validInterval(saved?.viewport) ? saved!.viewport! : cut != null ? [Math.max(1, cut - 11), Math.min(length, cut + 12)] : [1, Math.min(length, 40)]);
  const [selected, setSelected] = useState(Number.isInteger(saved?.selected) && Number(saved?.selected) >= 1 && Number(saved?.selected) <= length ? Number(saved?.selected) : cut != null ? Math.min(length, cut + 1) : 1);
  const [tracks, setTracks] = useState<string[]>(Array.isArray(saved?.tracks) ? [...new Set(saved!.tracks!.filter(k => properties.slice(0, 6).includes(k)))] : ['hydrophobicity', 'charge', 'flexibility']);
  const [showEst, setShowEst] = useState(saved?.showEst ?? true);
  const [tab, setTab] = useState(['sequence', 'metrics', 'evidence', 'index'].includes(saved?.tab || '') ? saved!.tab! : 'sequence');
  const [scope, setScope] = useState(saved?.scope ?? (cut != null ? 'SP' : 'whole')), [metricProperty, setMetricProperty] = useState(saved?.property || ''), [process, setProcess] = useState(saved?.process || ''), [query, setQuery] = useState(saved?.query || '');
  const [detail, setDetail] = useState<string | null>(null), [exportMessage, setExportMessage] = useState('');
  const filtered = filterMetrics(result, { scope, property: metricProperty, process, query, estimates: showEst });
  useEffect(() => { track('filter_changed','filters',{hits:filtered.length,filled:!!query,estimated:showEst,scope:contract.enums.scope.includes(scope)?scope:scope?'other':'all',property:contract.enums.property.includes(metricProperty)?metricProperty:metricProperty?'other':'all',process:contract.enums.process.includes(process)?process:process?'other':'all'}); },[scope,metricProperty,process,query,showEst]);
  useEffect(() => { onView?.({ selected, selection, viewport, tracks, showEst, scope, property: metricProperty, process, query, tab }); }, [selected, selection, viewport, tracks, showEst, scope, metricProperty, process, query, tab, onView]);
  function selectRange(range: Interval) { const value = clampInterval(range[0], range[1], length); setSelection(value); setViewport(focusViewport(value, length)); setSelected(p => p >= value[0] && p <= value[1] ? p : cut != null && cut + 1 >= value[0] && cut + 1 <= value[1] ? cut + 1 : value[0]); }
  function selectPosition(position: number, extend: boolean) { if (extend) setSelection(clampInterval(selected, position, length)); else { setSelected(position); setSelection([position, position]); } }
  function hideEstimates(value: boolean) { setShowEst(value); if (!value && result.regions.basis === 'rule_estimate' && ['N', 'H', 'C'].includes(scope)) setScope(cut != null ? 'SP' : 'whole'); }
  function saveAnalysis() { track('export_requested','export',{kind:'json',outcome:'requested'}); saveFile('signal-peptide-analysis.json', JSON.stringify({ ...record, view: { selected, selection, viewport, tracks, showEst, scope, property: metricProperty, process, query, tab } }, null, 2)); setExportMessage(t('解析JSONを保存しました。配列、注釈、指標、表示範囲を含みます。', 'Saved analysis JSON, including sequence, annotations, metrics and view settings.')); }
  function csv(all: boolean) { track('export_requested','export',{kind:'csv',outcome:'requested'}); saveFile(all ? 'signal-peptide-all-metrics.csv' : 'signal-peptide-filtered-metrics.csv', '\uFEFF' + metricCSV(all ? result.metrics : filtered), 'text/csv;charset=utf-8'); setExportMessage(t(`${all ? result.metrics.length : filtered.length}指標をCSVに保存しました。`, `Saved ${all ? result.metrics.length : filtered.length} descriptors as CSV.`)); }
  function saveProfile() { track('export_requested','export',{kind:'csv',outcome:'requested'});
    const columns = ['position', 'residue', 'relative', 'region', ...properties.slice(0, 6)], quote = (x: unknown) => `"${String(x ?? '').replaceAll('"', '""')}"`;
    saveFile('signal-peptide-selected-residues.csv', '\uFEFF' + [columns.join(','), ...result.profiles.slice(selection[0] - 1, selection[1]).map(row => columns.map(key => quote(row[key])).join(','))].join('\r\n'), 'text/csv;charset=utf-8');
    setExportMessage(t(`選択範囲${selection.join('–')}の残基尺度を保存しました。尺度の出所は解析JSONに記録しています。`, `Saved coefficients for ${selection.join('–')}. Scale provenance is in the analysis JSON.`));
  }
  function saveSVG() { track('export_requested','export',{kind:'svg',outcome:'requested'});
    if (!tracks.length) return;
    const sections = exportedTracks(result, tracks, viewport, selection, selected, t);
    const fragments = [...sections.matchAll(/<svg[^>]*>([\s\S]*?)<\/svg>/g)];
    const parts = fragments.map((fragment, i) => `<g transform="translate(0 ${i * 170})"><text x="58" y="16" font-size="14">${safeHTML(t(scales[tracks[i]].ja, scales[tracks[i]].en))} · ${safeHTML(scales[tracks[i]].source)}</text><g transform="translate(0 24)">${fragment[1]}</g></g>`).join('');
    saveFile('signal-peptide-property-tracks.svg', `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 ${170 * tracks.length + 38}"><title>${safeHTML(recordName(record, t))} · ${viewport.join('–')}</title><rect width="1000" height="100%" fill="white"/>${parts}<text x="58" y="${170 * tracks.length + 22}" font-size="12">${safeHTML(t('残基尺度値。切断効率・分泌量・実際の剛直性を表す値ではありません。', 'Residue coefficients; not cleavage efficiency, secretion yield or physical rigidity.'))}</text></svg>`, 'image/svg+xml'); setExportMessage(t('選択した物性トラックをSVGに保存しました。', 'Saved selected property tracks as SVG.'));
  }
  function reportHTML() { track('export_requested','export',{kind:'html',outcome:'requested'});
    const rows = result.metrics.map(m => `<tr><td>${safeHTML(t(m.label_ja, m.id))}</td><td>${safeHTML(formatValue(m.value))}</td><td>${safeHTML(metricUnit(m, t))}</td><td>${safeHTML(scopeLabel(m.scope, t))} ${m.range.join('–')}</td><td>${safeHTML(basisLabel(m.basis, t))}</td><td>${safeHTML(metricDefinition(m, t))}<br>${safeHTML(m.source)}</td></tr>`).join('');
    const graph = exportedTracks(result, tracks, viewport, selection, selected, t);
    saveFile('signal-peptide-report.html', `<!doctype html><html lang="${t('ja', 'en')}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${safeHTML(recordName(record, t))} — Signal Peptide Explorer</title><style>body{font:14px/1.6 system-ui,sans-serif;color:#243442;max-width:1100px;margin:30px auto;padding:0 20px}table{border-collapse:collapse;width:100%;font-size:12px}th,td{padding:8px;border:1px solid #cbd3da;text-align:left;vertical-align:top}svg{width:100%;height:auto}code,pre{white-space:pre-wrap;overflow-wrap:anywhere}.track-heading{display:flex;gap:16px;align-items:center}.track-note{font-size:12px}details{margin-top:24px}@media print{body{margin:0}tr{break-inside:avoid}}</style></head><body><h1>${safeHTML(recordName(record, t))}</h1><p>Signal Peptide Explorer · ${safeHTML(result.created_at)} · ${safeHTML(result.sequence_sha256)}</p><p>${safeHTML(record.metadata.organism)} ${safeHTML(record.metadata.accession)}</p><h2>${safeHTML(t('注釈と解析条件', 'Annotations & settings'))}</h2><table><tr><th>SP</th><th>${safeHTML(t('切断位置', 'Cleavage'))}</th><th>${safeHTML(t('種類', 'Type'))}</th></tr><tr>${['has_sp', 'cleavage', 'type'].map(key => `<td>${safeHTML(annotationLabel(result, key, t))}<br>${safeHTML(basisLabel(result.annotations[key].basis, t))}</td>`).join('')}</tr></table><p>N/H/C: ${safeHTML(basisLabel(result.regions.basis, t))} · ${safeHTML(result.regions.method)} · ${safeHTML(t('成熟側の集計範囲', 'Mature window'))}: ${result.settings.mature_window} aa</p><h2>${safeHTML(t('解釈の範囲', 'Interpretation limits'))}</h2><ul>${result.warnings.map(w => `<li>${safeHTML(warningLabel(w, t))}</li>`).join('')}</ul><h2>${safeHTML(t('選択範囲', 'Selected interval'))}: ${selection.join('–')}</h2><code>${safeHTML(result.sequence.slice(selection[0] - 1, selection[1]))}</code>${graph}<h2>${safeHTML(t('全指標', 'All descriptors'))}</h2><table><thead><tr>${[t('指標', 'Metric'), t('値', 'Value'), t('単位', 'Unit'), t('範囲', 'Interval'), t('範囲・注釈の由来', 'Boundary / annotation basis'), t('定義・出所', 'Definition & source')].map(s => `<th>${safeHTML(s)}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table><details><summary data-ux="workspace-summary-001">${safeHTML(t('再現用の解析記録', 'Reproducible analysis record'))}</summary><pre>${safeHTML(JSON.stringify({ ...record, view: { selected, selection, viewport, tracks, showEst, scope, property: metricProperty, process, query, tab } }, null, 2))}</pre></details></body></html>`, 'text/html'); setExportMessage(t('全指標と解析条件を含むHTMLレポートを保存しました。ブラウザーからPDFにも印刷できます。', 'Saved a self-contained HTML report with all descriptors and settings. Print it to PDF from your browser.'));
  }
  const mainWarnings = result.warnings.filter(w => !w.startsWith('Sequence coefficients') && !w.startsWith('Matrix links'));
  const tabs: [string, string][] = [['sequence', t('配列・切断点', 'Sequence & cleavage')], ['metrics', t('指標一覧', 'Metrics')], ['evidence', t('根拠・解析条件', 'Evidence & settings')], ['index', t('指標を探す', 'Descriptor index')]];
  return <>
    <section className="entry-header"><div className="entry-title"><div><span className="entry-type">{t('配列解析結果', 'Sequence analysis result')}</span><h1>{recordName(record, t)}</h1><p>{length} aa · {result.mode === 'sp' ? t('SPのみ', 'SP only') : t('前駆体', 'Precursor')}{record.metadata.organism && <> · {record.metadata.organism}</>}{record.metadata.accession && <> · {record.metadata.accession}</>}<span className="metadata-origin">{(record.metadata.organism || record.metadata.accession) && t('（入力情報）', '(supplied)')}</span></p></div><div className="entry-actions"><button data-ux="workspace-button-002" onClick={() => onEdit()}>{t('入力・注釈を編集', 'Edit input & annotations')}</button><button data-ux="workspace-button-003" className="primary" onClick={saveAnalysis}>{t('解析を保存', 'Save analysis')}</button></div></div>
      <dl className="annotation-summary">{[['has_sp', t('SPの有無', 'SP presence')], ['cleavage', t('切断位置', 'Cleavage')], ['type', t('SPの種類', 'SP type')]].map(([key, label]) => <div key={key}><dt>{label}</dt><dd>{annotationLabel(result, key, t)}<span className={`basis-tag ${result.annotations[key].basis}`}>{basisLabel(result.annotations[key].basis, t)}</span></dd></div>)}</dl>

    </section>

    {mainWarnings.some(w => w.startsWith('Supplied') || w.startsWith('Predicted')) && <details className="annotation-alert"><summary data-ux="workspace-summary-conflict">{t('入力注釈と予測に相違あり · 入力を優先', 'Input and prediction differ · supplied annotations retained')}</summary>{mainWarnings.filter(w => w.startsWith('Supplied') || w.startsWith('Predicted')).map((w,i)=><p key={i}>{warningLabel(w,t)}</p>)}</details>}
    <div className="result-toolbar"><nav className="result-tabs" aria-label={t('解析結果の表示', 'Result views')}>{tabs.map(([key, label]) => <button data-ux="workspace-button-005" key={key} aria-current={tab === key ? 'page' : undefined} onClick={() => { setTab(key); setDetail(null); }}>{label}</button>)}</nav><details className="export-menu"><summary data-ux="workspace-summary-006">{t('図・表・レポートを出力', 'Export figures & data')}</summary><div className="export-options"><button data-ux="workspace-button-007" onClick={() => csv(true)}>{t('全指標 · CSV', 'All descriptors · CSV')}</button><button data-ux="workspace-button-008" onClick={saveProfile}>{t('選択残基の物性 · CSV', 'Selected residue coefficients · CSV')}</button><button data-ux="workspace-button-009" onClick={saveSVG} disabled={!tracks.length}>{t('表示中の物性図 · SVG', 'Visible property tracks · SVG')}</button><button data-ux="workspace-button-010" onClick={reportHTML}>{t('解析レポート · HTML', 'Analysis report · HTML')}</button><button data-ux="workspace-button-011" onClick={() => { track('export_requested','export',{kind:'print',outcome:'requested'}); window.print(); }}>{t('現在の結果を印刷・PDF', 'Print current view / PDF')}</button></div></details></div>
    {exportMessage && <p className="export-message" role="status">{exportMessage}</p>}
    {tab === 'sequence' && <SequenceViewer onEdit={onEdit} result={result} selected={selected} selection={selection} viewport={viewport} estimates={showEst} tracks={tracks} t={t} onSelect={selectPosition} onRange={selectRange} onViewport={setViewport} onEstimates={hideEstimates} onTracks={setTracks} />}
    {tab === 'metrics' && <section className="panel metrics-panel"><div className="panel-heading"><div><h2>{t('領域別の指標', 'Interval descriptors')}</h2><p>{t('集計範囲を選び、必要な指標を絞り込みます。値の定義と出所は各行から確認できます。', 'Choose an interval and filter descriptors. Open a row to inspect its definition and source.')}</p></div><button data-ux="workspace-button-012" onClick={() => csv(false)} disabled={!filtered.length}>{t('表示中の指標をCSV保存', 'Export filtered metrics')}</button></div>
      <div className="metric-filters"><label>{t('集計範囲', 'Scope')}<select data-ux="workspace-select-013" value={scope} onChange={e => setScope(e.target.value)}><option value="">{t('すべての範囲', 'All scopes')}</option>{[...new Set(result.metrics.filter(m => showEst || m.basis !== 'rule_estimate').map(m => m.scope))].map(s => <option key={s} value={s}>{scopeLabel(s, t)}</option>)}</select></label><label>{t('物性・特性', 'Property')}<select data-ux="workspace-select-014" value={metricProperty} onChange={e => setMetricProperty(e.target.value)}><option value="">{t('すべての特性', 'All properties')}</option>{[...new Set(result.metrics.map(m => m.property))].map(p => <option key={p} value={p}>{scales[p] ? t(scales[p].ja, scales[p].en) : p}</option>)}</select></label><label>{t('生理学的な分類', 'Physiological context')}<select data-ux="workspace-select-015" value={process} onChange={e => setProcess(e.target.value)}><option value="">{t('すべての分類', 'All contexts')}</option>{Object.keys(result.matrix.processes).map(p => <option key={p} value={p}>{processLabel(p, t)}</option>)}</select></label><label className="search-field">{t('指標を検索', 'Find descriptors')}<input data-ux="workspace-input-016" type="search" value={query} onChange={e => setQuery(e.target.value)} placeholder={t('指標名・尺度・識別子', 'Name, scale or identifier')} /></label></div>
      <div className="filter-status"><span>{filtered.length} / {result.metrics.length} {t('指標', 'descriptors')}</span><label className="checkbox"><input data-ux="workspace-input-017" type="checkbox" checked={showEst} onChange={e => hideEstimates(e.target.checked)} />{t('規則で推定した領域を含む', 'Include rule-estimated intervals')}</label><button data-ux="workspace-button-018" className="text-button" onClick={() => { setScope(''); setMetricProperty(''); setProcess(''); setQuery(''); setDetail(null); }}>{t('絞り込みを解除', 'Clear filters')}</button></div>
      <div className="table-container"><table className="metrics-table"><thead><tr><th>{t('指標', 'Descriptor')}</th><th>{t('値', 'Value')}</th><th>{t('単位', 'Unit')}</th><th>{t('集計範囲', 'Interval')}</th><th>{t('範囲・注釈の由来', 'Boundary / annotation basis')}</th><th>{t('詳細', 'Details')}</th></tr></thead><tbody>{filtered.map(m => <React.Fragment key={m.id}><tr><td>{t(m.label_ja, m.id)}</td><td className="numeric">{formatValue(m.value)}</td><td>{metricUnit(m, t)}</td><td><button data-ux="workspace-button-019" className="interval-link" onClick={() => { selectRange(m.range as Interval); setTab('sequence'); }}>{scopeLabel(m.scope, t)}<small>{m.range.join('–')}</small></button></td><td><span className={`basis-tag ${m.basis}`}>{basisLabel(m.basis, t)}</span><small>{m.scope === 'structure' ? t('外部注釈の由来', 'Imported annotation basis') : t('値は配列から計算', 'Value calculated from sequence')}</small></td><td><button data-ux="workspace-button-020" className="text-button" aria-expanded={detail === m.id} onClick={() => setDetail(detail === m.id ? null : m.id)}>{detail === m.id ? t('閉じる', 'Close') : t('定義・出所', 'Definition & source')}</button></td></tr>{detail === m.id && <tr className="metric-detail-row"><td colSpan={6}><MetricDetails metric={m} t={t} /></td></tr>}</React.Fragment>)}</tbody></table></div>
      {!filtered.length && <p className="empty-results">{t('この条件に該当する指標はありません。範囲や特性の指定を変更してください。', 'No descriptors match. Change the interval or property filters.')}</p>}<p className="muted">{t('生理学的な分類は指標を探すための整理です。物性値を切断効率や膜通過率として読むことはできません。', 'Physiological contexts are a discovery index. Values are not cleavage efficiencies or translocation rates.')}</p>
    </section>}
    {tab === 'index' && <section className="panel index-panel"><div className="panel-heading"><div><h2>{t('生理学的な文脈から指標を探す', 'Find descriptors by physiological context')}</h2><p>{t('関連する物性を選ぶと、指標一覧へ移動します。この表は分類の索引です。', 'Choose a related property to open the descriptor list. This is a classification index.')}</p></div></div><div className="table-container desktop-index"><table className="index-table"><thead><tr><th>{t('生理学的な文脈', 'Physiological context')}</th>{properties.map(p => <th key={p}>{t(scales[p].ja, scales[p].en)}</th>)}</tr></thead><tbody>{Object.keys(result.matrix.processes).map(p => <tr key={p}><th>{processLabel(p, t)}</th>{properties.map(key => <td key={key}>{result.matrix.relations[key]?.includes(p) ? <button data-ux="workspace-button-021" aria-label={`${processLabel(p, t)} · ${t(scales[key].ja, scales[key].en)}`} onClick={() => { setProcess(p); setMetricProperty(key); setScope(''); setQuery(''); setTab('metrics'); }}>{t('指標を見る', 'View')}</button> : <span title={t('この分類では直接対応する配列指標を登録していません。', 'No direct sequence descriptor registered for this context.')}>—</span>}</td>)}</tr>)}</tbody></table></div>
      <div className="mobile-index">{Object.keys(result.matrix.processes).map(p => <section key={p}><h3>{processLabel(p,t)}</h3><div className="button-group">{properties.filter(key => result.matrix.relations[key]?.includes(p)).map(key => <button data-ux="workspace-button-mobile-index" key={key} onClick={() => {setProcess(p);setMetricProperty(key);setScope('');setQuery('');setTab('metrics');}}>{t(scales[key].ja,scales[key].en)}</button>)}</div>{!properties.some(key=>result.matrix.relations[key]?.includes(p)) && <p>{t('対応する配列指標の登録なし', 'No sequence descriptor registered')}</p>}</section>)}</div>
      <h3>{t('構造情報や周辺条件が必要な項目', 'Items requiring structure or contextual information')}</h3><dl className="context-list"><div><dt>{t('切断部位への接近', 'Cleavage-site accessibility')}</dt><dd>{t('柔軟性参照値や残基体積は配列上の特徴です。実際の露出度や剛直性には、構造状態とその根拠が必要です。外部の構造注釈は詳細設定から読み込めます。', 'Flexibility and volume coefficients describe sequence features. Exposure and rigidity require structural evidence. Import annotations through Advanced settings.')}</dd></div><div><dt>{t('輸送経路・生物種・膜環境', 'Pathway, organism & membrane environment')}</dt><dd>{t('配列物性だけで確定できない条件です。SPの種類や元の注釈と併せて解釈します。', 'These conditions cannot be established from coefficients alone. Interpret them with SP type and source annotations.')}</dd></div><div><dt>{t('切断効率・分泌量', 'Cleavage efficiency & secretion yield')}</dt><dd>{t('このツールでは予測値を付与していません。指標を比較しても、効率の順位は得られません。', 'No prediction is provided. Comparing descriptors does not yield efficiency rankings.')}</dd></div></dl></section>}
    {tab === 'evidence' && <section className="panel evidence-panel"><h2>{t('注釈と解析条件', 'Annotations & settings')}</h2><div className="table-container"><table><thead><tr><th>{t('項目', 'Item')}</th><th>{t('値・範囲', 'Value / interval')}</th><th>{t('由来・方法', 'Basis / method')}</th></tr></thead><tbody>{['has_sp', 'cleavage', 'type'].map(key => <tr key={key}><th>{key === 'has_sp' ? t('SPの有無', 'SP presence') : key === 'cleavage' ? t('切断位置', 'Cleavage') : t('SPの種類', 'SP type')}</th><td>{annotationLabel(result, key, t)}</td><td>{basisLabel(result.annotations[key].basis, t)}{result.annotations[key].method && <small>{result.annotations[key].method}</small>}</td></tr>)}{Object.entries(result.regions.intervals || {}).map(([key, range]) => <tr key={key}><th>{key} {t('領域', 'region')}</th><td>{range.join('–')}</td><td>{basisLabel(result.regions.basis, t)}</td></tr>)}<tr><th>{t('成熟側の集計範囲', 'Mature N-terminal window')}</th><td>{result.settings.mature_window} aa</td><td>{t('＋1から指定残基数、入力末端まで', 'From +1 for the requested count, capped at the input terminus')}</td></tr></tbody></table></div>
      <h3>{t('この解析に付随する注意', 'Interpretation notes for this analysis')}</h3><ul className="evidence-notes">{result.warnings.map((w, i) => <li key={i}>{warningLabel(w, t)}</li>)}</ul><dl className="provenance-list"><div><dt>{t('解析日時', 'Analysis time')}</dt><dd>{result.created_at || t('記録なし', 'Not recorded')}</dd></div><div><dt>{t('科学計算の実装', 'Scientific implementation')}</dt><dd>{result.software?.name || 'signal-peptide-features'} {result.software?.version}<small>{result.execution || t('設定された解析サーバー', 'Configured analysis server')}</small></dd></div><div><dt>{t('実装SHA256', 'Implementation SHA256')}</dt><dd><code>{result.software?.implementation_sha256 || '—'}</code></dd></div><div><dt>{t('入力配列SHA256', 'Input sequence SHA256')}</dt><dd><code>{result.sequence_sha256}</code></dd></div><div><dt>{t('参照尺度の記録', 'Reference scale record')}</dt><dd>{result.references?.source && <a data-ux="workspace-a-022" href={result.references.source} target="_blank" rel="noreferrer">AAindex</a>}<small>{result.references?.retrieved} · {result.references?.sha256}</small></dd></div></dl><details className="methods-details"><summary data-ux="workspace-summary-methods">{t('計算方法・参照尺度・peptidesとの違い', 'Methods, scales & differences from peptides')}</summary><Guide t={t} /></details><details className="raw-record"><summary data-ux="workspace-summary-023">{t('予測・注釈の元の記録（JSON）', 'Original prediction & annotation records (JSON)')}</summary><pre>{JSON.stringify({ annotations: result.annotations, regions: result.regions, prediction: result.prediction, references: result.references }, null, 2)}</pre></details></section>}
    <section className="advanced-section"><details><summary data-ux="workspace-summary-024">Advanced · {t('解析済み配列の比較・履歴', 'Compare analyzed sequences & session history')} <span>{history.length} {t('件', 'results')}</span></summary><p>{t('履歴はこの画面を開いている間だけ保持します。再利用する解析はJSONで保存してください。比較する配列は一つずつ解析するか、保存JSONから読み込みます。', 'Session history lasts while this page is open. Save JSON for reuse. Analyze individually, or import saved results to compare.')}</p><FileButton label={t('保存した解析JSONを開く', 'Open saved analysis JSON')} accept=".json" onFile={onOpen} /><ul className="history-list">{history.map((r, i) => <li key={`${r.analysis.sequence_sha256}-${i}`}><button data-ux="workspace-button-025" className="text-button" onClick={() => onRestore(r)}>{recordName(r, t)}</button><span>{r.analysis.sequence.length} aa · {t('切断', 'cleavage')} {annotationLabel(r.analysis, 'cleavage', t)}</span></li>)}</ul>{history.length >= 2 ? <Comparison records={history} t={t} /> : <p className="notice">{t('二つ以上の解析結果を読み込むと、同じ指標を比較できます。', 'Load at least two analyses to compare matching descriptors.')}</p>}</details></section>
  </>;
}
function MetricDetails({ metric: m, t }: { metric: Metric; t: Translate }) {
  const url = sourceURL(m.source);
  return <dl className="metric-details"><div><dt>{t('指標ID', 'Descriptor ID')}</dt><dd><code>{m.id}</code></dd></div><div><dt>{t('定義', 'Definition')}</dt><dd>{metricDefinition(m, t)}</dd></div><div><dt>{t('尺度・出所', 'Scale / source')}</dt><dd>{url ? <a data-ux="workspace-a-026" href={url} target="_blank" rel="noreferrer">{m.source}</a> : m.source}</dd></div><div><dt>{t('計算範囲', 'Calculated interval')}</dt><dd>{scopeLabel(m.scope, t)} · {m.range.join('–')} · {m.range[1] - m.range[0] + 1} aa</dd></div><div><dt>{t('単位・値の表現', 'Units / representation')}</dt><dd>{metricUnit(m, t)}</dd></div><div><dt>{t('切断境界の由来', 'Cleavage boundary basis')}</dt><dd>{m.scope === 'whole' ? t('切断境界を使わない集計', 'Independent of cleavage') : basisLabel(m.boundary_basis, t)}</dd></div><div><dt>{t('検証記録', 'Verification record')}</dt><dd>{m.source_verification}</dd></div></dl>;
}
function Comparison({ records, t }: { records: RecordEntry[]; t: Translate }) {
  const [scope, setScope] = useState(records.some(r => r.analysis.metrics.some(m => m.scope === 'SP')) ? 'SP' : 'whole'), [all, setAll] = useState(false);
  const scopes = [...new Set(records.flatMap(r => r.analysis.metrics.map(m => m.scope)))], ids = [...new Set(records.flatMap(r => r.analysis.metrics.filter(m => m.scope === scope && (all || !m.id.includes('.fraction_'))).map(m => m.id)))];
  return <><div className="comparison-controls"><label>{t('比較する範囲', 'Scope to compare')}<select data-ux="workspace-select-027" value={scope} onChange={e => setScope(e.target.value)}>{scopes.map(s => <option key={s} value={s}>{scopeLabel(s, t)}</option>)}</select></label><label className="checkbox"><input data-ux="workspace-input-028" type="checkbox" checked={all} onChange={e => setAll(e.target.checked)} />{t('全組成指標を含む', 'Include all composition fractions')}</label></div><p className="muted">{t('同じ名前の指標を並べた記述的な比較です。各値の残基範囲と境界の由来も表示します。配列の位置合わせや効率の順位付けは行いません。', 'Descriptive comparison of matching identifiers with intervals and provenance. No sequence alignment or efficiency ranking is performed.')}</p><div className="table-container"><table><thead><tr><th>{t('指標', 'Descriptor')}</th>{records.map((r, i) => <th key={i}>{recordName(r, t)}<small>{r.analysis.sequence.length} aa · {annotationLabel(r.analysis, 'type', t)}</small></th>)}</tr></thead><tbody>{ids.map(id => { const reference = records.flatMap(r => r.analysis.metrics).find(m => m.id === id)!; return <tr key={id}><th>{t(reference.label_ja, reference.id)}<small>{metricUnit(reference, t)}</small></th>{records.map((r, i) => { const m = r.analysis.metrics.find(m => m.id === id); return <td key={i}>{m ? <>{formatValue(m.value)}<small>{m.range.join('–')} · {basisLabel(m.basis, t)}</small></> : '—'}</td>; })}</tr>; })}</tbody></table></div>{!ids.length && <p>{t('この範囲の指標はありません。別の範囲を選んでください。', 'No descriptors for this scope. Choose another scope.')}</p>}</>;
}
